server:
  port: 80

eureka:
  instance:
    prefer-ip-address: true

spring:
  devtools:
    add-properties: false

  datasource:
    url: jdbc:mysql://fiction-db-0.fiction-db.cangjingge.svc.cluster.linc:3306/cangjingge?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: cangjingge
