server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://eureka.default/eureka/

spring:
  devtools:
    add-properties: false

  datasource:
    url: jdbc:mysql://localhost:3306/cangjingge?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
