spring:
  profiles:
    active: "@activatedProperties@"

  application:
    name: zuul-gateway

eureka:
  instance:
    instance-id: zuul

zuul:
  routes:
    auth:
      path: /auth/**
      serviceId: authorization
    fiction:
      path: /fictions/**
      serviceId: fiction
    user:
      path: /users/**
      serviceId: user
    fiction-review:
      path: /fiction-reviews/**
      serviceId: fiction-review
  ignored-services: "*"
  sensitive-headers: Cookie,Set-Cookie
  ignored-patterns: /auth/token/validation
