spring:
  profiles:
    active: "@activatedProperties@"

  application:
    name: authorization

  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"

eureka:
  instance:
    instance-id: authorization
