apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization
  namespace: cangjingge
spec:
  selector:
    matchLabels:
      app: authorization
  template:
    metadata:
      labels:
        app: authorization
    spec:
      restartPolicy: Always
      containers:
      - name: authorization
        image: lgasyou/cangjingge-authorization:0.1.3
        env:
          - name: APP_OPTS
            valueFrom:
              configMapKeyRef:
                key: default-zone
                name: eureka-server-configmap
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 5
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
