apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: cangjingge
  labels:
    app: eureka-server
spec:
  ports:
    - port: 80
      name: eureka
  clusterIP: None
  selector:
    app: eureka-server
