apiVersion: v1
kind: Service
metadata:
  name: zuul-gateway
  namespace: cangjingge
spec:
  type: NodePort
  selector:
    app: zuul-gateway
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 8080
