apiVersion: v1
kind: Service
metadata:
  name: zuul-gateway
  namespace: cangjingge
spec:
  type: NodePort
  selector:
    app: zuul-gateway
  ports:
    - port: 80
      targetPort: 80
      nodePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-gateway
  namespace: cangjingge
spec:
  selector:
    matchLabels:
      app: zuul-gateway
  template:
    metadata:
      labels:
        app: zuul-gateway
    spec:
      restartPolicy: Always
      containers:
      - name: zuul-gateway
        image: lgasyou/cangjingge-zuul-gateway:0.1.1
        env:
          - name: APP_OPTS
            valueFrom:
              configMapKeyRef:
                key: default-zone
                name: eureka-server-configmap
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 5
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
