server:
  port: 80

eureka:
  instance:
    hostname: eureka
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  devtools:
    add-properties: false
